### PR TITLE
Iasyncenumerable

### PR DESCRIPTION
**Pull request by BionicCode**
- Merge changes from #41 to branch iasyncenumerable
  - Target #39: Fixed LINQ expression to use the conditional `Enumerable.FirstOrDefault` instead of `Enumerable.First` in `DeviceLocator.GetMulticastIPAddressesForDiscovery`. `DeviceLocator.GetMulticastIPAddressesForDiscovery` now returns an empty `IEnumerable` in case the condition is never satisfied.

  - Improve API: Changed `DiscoverAsync` to return a `IEnumerable<Device>` instead of a `List<T`. Method signature remains unchanged. Basically removed call to `Enumerable.ToList` to defer the execution of the query in order to improve performance (especially in situations where the caller wants to iterate over/filter the result collection).

  -  Add cancellation support to asynchronous API by providing corresponding overloads (non-breaking change)

  - Update old XML documantation

  - Add/improve XML documantation

  - Run Resharper code cleanup (fix indention and formatting).

- Fix/Implement `IAsyncEnumerable EnumerateDevicesAsync(void)` and `IAsyncEnumerable EnumerateDevicesAsync(CancellationToken)`
- Implement `EnumerateDevicesAsync` overload which accepts `NetworkInterface`. 
- Fix Dispose pattern in `Device`. 
- Fix test case after renaming method to `EnumerateDevicesAsync`. 
- Add `EnumeratorCancellation` attribute to `IAsyncEnumerable` methods. 
- Refactored `DeviceLocator` device lookup (`GetDevicesFromSocket` in particular) to support enumeration (may improve performance).
- Add throw `DeviceDeiscoveryException` when a `SocketException` was thrown and no device was found (optimistic exception handling - if exception was thrown but at least one device was discovered no exception will be thrown). 
- Add `DeviceDiscoveryException` as major excpetion of `DeviceLocator` and as a wrapper of any `SocketException` that was thrown during the discovery."

### CODE REVIEW

**Comment by roddone** [comment]
One again you give me hard work to review this PR @BionicCode 😂 I will have a look on this as soon as I can.

In the meantime, could #41 be closed ? I assume it can because all your work is also in this PR ?

**Comment by BionicCode** [comment]
Ahaha :grinning: So true. I just came around to keep you busy, no time for the lazy :stuck_out_tongue_winking_eye: Yes, #41 can be closed. I've merged the fix into this branch to keep it simple.

**Comment by BionicCode** [comment]
I also think you can close the bug ticket #39 too. Obviously the origin of the error is on the client side. Or as you suggested may be a subject to the quota. Still, there is a small chance that the creation of the `Socket` fails. `SocketException` is currently silenced. I suggest to cache the first or all occurring `SocketException`, so that we can throw them in case discovery failed to succeed. If discovery failed (all retries are without a result) AND a `SocketException` occurred, then we can assume that this exception is the result of network issues or invalid parameters. Throwing a custom wrapper exception e.g. `DeviceDiscoveryException` that contains all thrown `SocketException` objects can help the client to figure out and fix networking or parameters issues. I can add quickly. The owner of ticket #39 then could use this version to test it.

**Comment by BionicCode** [comment]
:hankey: Done...

**Comment by roddone** [comment]
@BionicCode do you use a specific tool for the indentation/refactoring ? It introduces a lot a line breaks that makes it difficult to review correctly and merge other commits and PR. 

For example, I am working on a new feature for #40 on branch `feature/music-mode` and I think I am going to get some troubles when time will come to merge everything in master 😂

**Comment by roddone** [comment]
In fact, I think the problems will only occur in `Device.cs` which should not not belong to this PR since it has nothing in common with the IAsyncEnumerable nor the Discovery.

I think we should move changes to Device.cs in another PR, maybe we can do it directly to `feature/music-mode` that will also be merged in master as soon as this feature is working ?

**Comment by BionicCode** [comment]
@roddone  Yes, I know :confused: Shame on me. The formatting was not a very nice move of mine. Especially as I don't know your code conventions. I copied and moved some code around and in some places the indentation broke and I don't wanted to fix it manually. I usually use Resharper code cleanup and usually I apply it on the complete file. For example I  configured it to use 1 tab (2 spaces) for indention. I should have asked you before. 

To configure this is really done fast. You can give me your basic code conventions like indentation and braces rules then I can fix it. The changes in Device.cs were soo small. I think I implemented the Dispose pattern and added one or two braces for single lined if-statements (using code cleanup). That's why I included it in the same branch or PR. Honestly, I don't remember how I got to touch this file. I'm sorry for causing confusion. If it's about `Device.cs` then just ignore the related changes. Otherwise let me know, then I'd pull the relevant branch and merge it locally. 

I just got myself involved, I admit. It was just spontaneous. I really hope it's ok. By the way I know I should have applied for the issue. You then could've officially assigned it to me. Otherwise we or I risk to do double or redundant work. I mean it was assigned to you already. Oh man, I really messed up :clap: lol Let me know if I can do something to ease the pain 😃

**Comment by BionicCode** [comment]
How are you doing with the music mode. You get things going?

**Comment by roddone** [comment]
Don't worry, we just need to ajust to the same conventions 😉
Usually I don't use any tools like ReSharper for public projects because you can't be sure other people will use the same tools as you do. Although I do it at work with my teams.
For public projects I prefer keeping VS default indent and rules. 

Music mode is going well, it's almost done, but my main obstacle is the lack of free time to do it... I'm pretty sure I will be able to do the next release next week. It will include this PR and the music mode 😉

**Comment by BionicCode** [comment]
Yes I am using R# at work too, loving it. So I do some thinks like code cleanup automatically without reflecting it.

I have cleaned up the changesets. I have removed the changes related to Devices.cs. I've done it in a separate branch. D you want me to open a PR or have you already merged the previous sets? I would recommend taking the clean_up version. Might be less trouble for you to merge it.

**Comment by BionicCode** [comment]
I have just created a new PR. It's up to you to close this here and take the new #44 😃

**Comment by roddone** [comment]
Sorry for the delay, I haven't done any merge for the music mode yet so youre free to do a PR in `feature/music-mode` branch 😉

In the meantime I close this PR and finish the review of #44 .

**Pull request closed without merging**
